# Entrenamiento

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv('dataset_entrenamiento.csv', header='infer')

In [3]:
df

,pca1,pca2,pca3,pca4,pca5,pca6,pca7,pca8,pca9,pca10,price
0,-1.135995,0.535012,0.816425,-0.050794,-0.304979,-0.279575,-0.579169,-0.317794,0.691269,0.739567,25000
1,-1.377281,0.372810,0.907108,-0.076750,-0.198372,-0.033634,-0.513241,-0.253030,0.833272,0.734114,26883
2,-1.165785,0.146931,0.603021,-0.080559,-0.947686,0.120579,-0.168880,0.569587,0.482402,0.414872,20000
3,-1.951762,0.368694,-0.271449,-0.806649,0.412205,-0.045421,-0.769890,-0.280681,0.137348,0.759014,33492
4,-1.680660,-0.315905,-0.407757,-0.432229,0.422361,-0.667771,0.452300,0.250153,-0.029695,0.749164,22900
...,...,...,...,...,...,...,...,...,...,...,...
108534,-1.384441,-1.526891,-0.537479,0.061769,-0.270381,-0.431901,-0.256841,0.092623,-0.036481,-0.026341,16999
108535,-1.474025,-1.535904,-0.544550,0.118952,-0.251207,-0.383243,-0.239284,0.110359,-0.000383,-0.025875,16999
108536,-1.509383,-1.559673,-0.531261,0.115148,-0.235584,-0.347203,-0.229623,0.119849,0.020427,-0.026674,17199
108537,-0.828102,-0.185736,-0.570078,0.077447,0.858628,0.081404,-0.453364,-0.484825,0.411528,0.297343,19499
108538,-0.378708,-0.235070,-1.069985,0.061700,0.260367,0.432286,-0.003983,0.379704,0.210961,-0.013706,15999

In [4]:
Y = df['price']
X = df[df.columns.difference(['price'])]

In [5]:
X

,pca1,pca10,pca2,pca3,pca4,pca5,pca6,pca7,pca8,pca9
0,-1.135995,0.739567,0.535012,0.816425,-0.050794,-0.304979,-0.279575,-0.579169,-0.317794,0.691269
1,-1.377281,0.734114,0.372810,0.907108,-0.076750,-0.198372,-0.033634,-0.513241,-0.253030,0.833272
2,-1.165785,0.414872,0.146931,0.603021,-0.080559,-0.947686,0.120579,-0.168880,0.569587,0.482402
3,-1.951762,0.759014,0.368694,-0.271449,-0.806649,0.412205,-0.045421,-0.769890,-0.280681,0.137348
4,-1.680660,0.749164,-0.315905,-0.407757,-0.432229,0.422361,-0.667771,0.452300,0.250153,-0.029695
...,...,...,...,...,...,...,...,...,...,...
108534,-1.384441,-0.026341,-1.526891,-0.537479,0.061769,-0.270381,-0.431901,-0.256841,0.092623,-0.036481
108535,-1.474025,-0.025875,-1.535904,-0.544550,0.118952,-0.251207,-0.383243,-0.239284,0.110359,-0.000383
108536,-1.509383,-0.026674,-1.559673,-0.531261,0.115148,-0.235584,-0.347203,-0.229623,0.119849,0.020427
108537,-0.828102,0.297343,-0.185736,-0.570078,0.077447,0.858628,0.081404,-0.453364,-0.484825,0.411528
108538,-0.378708,-0.013706,-0.235070,-1.069985,0.061700,0.260367,0.432286,-0.003983,0.379704,0.210961

In [6]:
Y

0         25000
1         26883
2         20000
3         33492
4         22900
          ...
108534    16999
108535    16999
108536    17199
108537    19499
108538    15999
Name: price, Length: 108539, dtype: int64

## Division del conjunto de datos

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=4815)

In [9]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(75977, 10)
(75977,)
(32562, 10)
(32562,)

## Regresion con ElasticNet

In [14]:
alpha = [0.001, 0.0001, 0.00001]
l1_ratio = [0.001, 0.0001, 0.00001, 0.000001]
parameters = {'alpha': alpha, 'l1_ratio': l1_ratio}

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import ElasticNet

gridCV = GridSearchCV(ElasticNet(), parameters, cv=5, n_jobs = -1)       # "n_jobs = -1" means "use all the CPU cores".
gridCV.fit(X_train, Y_train)
best_alpha = gridCV.best_params_['alpha']
best_l1_ratio = gridCV.best_params_['l1_ratio']
print("Best alpha : " + str(best_alpha))
print("Best l1_ratio : " + str(best_l1_ratio))

Best alpha : 0.0001
Best l1_ratio : 1e-06

In [28]:
elasticNet_best = ElasticNet(alpha=best_alpha, l1_ratio=best_l1_ratio, random_state=4815, fit_intercept=False)
elasticNet_best.fit(X_train,Y_train)
Y_pred = elasticNet_best.predict(X_test)
print( "Best RMSE : " + str(np.round(mean_squared_error(Y_test,Y_pred,squared=False, multioutput='raw_values'),3)))

Best RMSE : [17525.614]